---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Background
This repository contains scripts used to perform heritability enrichment analyses using neurodegenerative GWASs and natural selection metrics.

# Citation
If you use any of the data from this repository, please cite our [paper](https://www.biorxiv.org/content/10.1101/2022.04.29.490053v1).

# License
The code in this repository is released under an MIT license. This repository is distributed in the hope that it will be useful to the wider community, but without any warranty of any kind. Please see the [LICENSE](LICENSE) file for more details. 

# Code contents

Within this repository you will find:

| Directory | Description |
| --------- | --------------------------------------------------------------------------- |
| [docs](docs) | Contains all `.Rmd`s and their corresponding `.html`s describing analyses performed for this project. These can be view interactively at: [https://rhreynolds.github.io/als-neanderthal-analysis/](https://rhreynolds.github.io/als-neanderthal-analysis/)|
| [logs](logs) | For any scripts that were run outside of an `.Rmd` (e.g. scripts from the [scripts](scripts) directory), a log file was recorded and can be accessed here. |
| [raw_data](raw_data)| Top percentiles of annotations. |
| [results](results) | Results from all analyses. |
| [scripts](scripts) | Contains analysis scripts. Each script contains a one-line description and is also referenced in its corresponding `.Rmd`. |